# Generated by Django 6.1 on 2026-08-22 17:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('job_role', models.CharField(max_length=200)),
                ('package_lpa', models.DecimalField(decimal_places=2, help_text='Package in LPA', max_digits=6)),
                ('drive_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('eligible_branches', models.CharField(help_text='Comma-separated branch codes, e.g. CSE,IT (leave blank for all branches)', max_length=200)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('max_backlogs_allowed', models.PositiveIntegerField(default=0)),
                ('required_skills', models.CharField(blank=True, help_text='Comma-separated, optional. Leave blank if no specific skill required.', max_length=300)),
                ('user', models.OneToOneField(blank=True, help_text='Login account for this company, created by the Placement Cell (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CSE', 'Computer Engineering'), ('IT', 'Information Technology'), ('ENTC', 'Electronics & Telecom'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil')], max_length=10)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('backlogs', models.PositiveIntegerField(default=0)),
                ('skills', models.CharField(help_text='Comma-separated, e.g. Python, Django, HTML', max_length=300)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('resume', models.FileField(blank=True, help_text='PDF only, max 5 MB.', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('interview_datetime', models.DateTimeField(blank=True, null=True)),
                ('interview_mode', models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=10)),
                ('interview_location', models.CharField(blank=True, help_text='Venue address (offline) or meeting link (online)', max_length=300)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.student')),
            ],
            options={
                'ordering': ['-applied_on'],
                'unique_together': {('student', 'company')},
            },
        ),
    ]
