# Generated by Django 6.1 on 2026-08-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='eligible_branches',
            field=models.CharField(blank=True, help_text='Comma-separated branch codes, e.g. CSE,IT (leave blank for all branches)', max_length=200),
        ),
    ]
